spring.application.name=agendamiento
server.port=8081

# Conexion a PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://navium-db-central.c3wswcuwyhon.us-east-1.rds.amazonaws.com:5432/navium_db?currentSchema=navium}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:naviumDB}
spring.datasource.currentSchema=navium

#Hibernate (Creación de tablas)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Conexión a RabbitMQ en la nube
spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://evzojucb:iRxjONsFNi5xHvj3imTD5El-i2F1ijjT@gerbil.rmq.cloudamqp.com/evzojucb}

#Clave para JWT
jwt.secret=${JWT_SECRET:NaviumSuperSecretKeyParaFirmaDeTokens2026!}

spring.main.allow-bean-definition-overriding=true
